### ISSUE TITLE
Rails app fails to boot with Frozen Error

### ISSUE THREAD

**Issue by dankeykang674** [getappmap/appmap-ruby#250]
Ruby version 2.7.2
Rails version 6.0.4

This only happens when I start the server with the `APPMAP=true` env var.

Stack trace of errors below:
```
❯ APPMAP=true bundle exec rails s -p 3000
=> Booting Puma
=> Rails 6.0.4.1 application starting in development 
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
	87: from bin/rails:3:in `<main>'
	86: from bin/rails:3:in `load'
	85: from /Users/my-user/dev/my-company/my-app/bin/spring:15:in `<top (required)>'
	84: from /Users/my-user/dev/my-company/my-app/bin/spring:15:in `require'
	83: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
	82: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
	81: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
	80: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
	79: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
	78: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
	77: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
	76: from /Users/my-user/dev/my-company/my-app/bin/rails:9:in `<top (required)>'
	75: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `require'
	74: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	73: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `block in require'
	72: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	71: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	70: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	69: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	68: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	67: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands.rb:18:in `<top (required)>'
	66: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/command.rb:46:in `invoke'
	65: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/command/base.rb:69:in `perform'
	64: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	63: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	62: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	61: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:138:in `perform'
	60: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:138:in `tap'
	59: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	58: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:37:in `start'
	57: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	56: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	55: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	54: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	53: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	52: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	51: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	50: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/appmap-0.83.1/lib/appmap/hook/method/ruby2.rb:50:in `block in hook_method_def'
	49: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/appmap-0.83.1/lib/appmap/hook/method/ruby2.rb:11:in `call'
	48: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/appmap-0.83.1/lib/appmap/handler/eval.rb:37:in `do_call'
	47: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/appmap-0.83.1/lib/appmap/handler/eval.rb:37:in `call'
	46: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/appmap-0.83.1/lib/appmap/handler/eval.rb:37:in `eval'
	45: from config.ru:4:in `block in <main>'
	44: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/appmap-0.83.1/lib/appmap/hook/method/ruby2.rb:50:in `block in hook_method_def'
	43: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/appmap-0.83.1/lib/appmap/hook/method/ruby2.rb:11:in `call'
	42: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/appmap-0.83.1/lib/appmap/hook/method/ruby2.rb:32:in `do_call'
	41: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/appmap-0.83.1/lib/appmap/hook/method/ruby2.rb:32:in `call'
	40: from /Users/my-user/dev/my-company/my-app/lib/app_booter.rb:32:in `boot'
	39: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/application.rb:363:in `initialize!'
	38: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:60:in `run_initializers'
	37: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	36: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	35: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	34: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
	33: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
	32: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	31: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	30: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `call'
	29: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	28: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:50:in `each'
	27: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	26: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	25: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `call'
	24: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	23: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:50:in `each'
	22: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	21: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	20: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `call'
	19: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	18: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:50:in `each'
	17: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	16: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	15: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:415:in `call'
	14: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	13: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:50:in `each'
	12: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	11: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	10: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	 9: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	 8: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	 7: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	 6: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 5: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	 4: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	 3: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:32:in `run'
	 2: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/initializable.rb:32:in `instance_exec'
	 1: from /Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/engine.rb:592:in `block in <class:Engine>'
/Users/my-user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/engine.rb:592:in `unshift': can't modify frozen Array: [] (FrozenError)
```

**Comment by kgilpin** [comment]
Thanks! We will take a look.

**Comment by dividedmind** [comment]
@dankeykang674 could you share your `config/routes.rb`? (Just general structure is quite enough, you can remove any specifics. I'm just wondering if there's anything unusual about it.)

**Comment by dankeykang674** [comment]
@dividedmind I don't think it's my routes. I tried deleting every single route and I still get the same error.

```
Rails.application.routes.draw do
  # All routes deleted
end
```

`ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.0.4.1/lib/rails/engine.rb:592:in `unshift': can't modify frozen Array: [] (FrozenError)`

**Comment by dividedmind** [comment]
I've spent some time trying to but I still can't reproduce the problem. Here are a couple of questions that came to mind, perhaps the answers will help me:
- What's your appmap.yml?
- Do you have any non-standard engines in the app?
- What does `lib/app_booter.rb` do?
- Anything else unusual about the app that could cause this, especially regarding manipulating routes?
