### ISSUE TITLE
Appmap error with forem: `TypeError: no implicit conversion of Hash into Integer`

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-ruby#305]
Got the following error trying to generate AppMaps for Forem's API v1:

```
~/src/forem$ APPMAP=true bundle exec rspec spec/requests/api/v1/
/home/test/.rbenv/versions/3.0.2/lib/ruby/3.0.0/digest.rb:6: warning: already initialized constant Digest::REQUIRE_MUTEX
/home/test/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/digest-3.1.0/lib/digest.rb:20: warning: previous definition of REQUIRE_MUTEX was here

An error occurred while loading ./spec/requests/api/v1/docs/reactions_spec.rb.
Failure/Error: end

TypeError:
  no implicit conversion of Hash into Integer
# ./app/models/reaction_category.rb:67:in `<class:ReactionCategory>'
# ./app/models/reaction_category.rb:2:in `<main>'
# ./spec/requests/api/v1/docs/reactions_spec.rb:37:in `block (4 levels) in <main>'
# ./spec/requests/api/v1/docs/reactions_spec.rb:26:in `block (3 levels) in <main>'
# ./spec/requests/api/v1/docs/reactions_spec.rb:25:in `block (2 levels) in <main>'
# ./spec/requests/api/v1/docs/reactions_spec.rb:24:in `block in <main>'
# ./spec/requests/api/v1/docs/reactions_spec.rb:7:in `<main>'


Finished in 0.00005 seconds (files took 4.5 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

These tests pass with `APPMAP=false`
```
~/src/forem$ APPMAP=false bundle exec rspec spec/requests/api/v1/
/home/test/.rbenv/versions/3.0.2/lib/ruby/3.0.0/digest.rb:6: warning: already initialized constant Digest::REQUIRE_MUTEX
/home/test/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/digest-3.1.0/lib/digest.rb:20: warning: previous definition of REQUIRE_MUTEX was here
[Zonebie] Setting timezone: ZONEBIE_TZ="Belgrade"
................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 1 minute 9.18 seconds (files took 3.6 seconds to load)
448 examples, 0 failures

[TEST PROF INFO] Time spent in factories: 00:51.297 (73.89% of total time)

```

**Comment by kgilpin** [comment]
Run with --backtrace option to get a long stack from rspec

**Comment by symwell** [comment]
Had better luck by running the API tests one by one

forem tests from spec/requests/api/v1/:

```
admin - passes
analytics_spec.rb - fails 1 testcase but passes the rest
articles_spec.rb - passes
comments_spec.rb - passes
display_ads_spec.rb - passes
docs/articles_spec.rb - fails
docs/display_ads_spec.rb - fails
docs/followers_spec.rb - fails
docs/podcast_episodes_spec.rb - fails
docs/profile_images_spec.rb - fails
docs/reactions_spec.rb - fails
docs/readinglist_spec.rb - fails
docs/users_spec.rb - fails
feature_flags_spec.rb - passes
followers_spec.rb - passes
follows_spec.rb - passes
health_checks_spec.rb - passes
instances_spec.rb - passes
listings_spec.rb - passes
organizations_spec.rb - passes
podcasts_episodes_spec.rb - passes
profile_images_spec.rb - passes
reactions_spec.rb - fails
readinglist_spec.rb - fails
tags_spec.rb - passes
users_spec.rb - passes
videos_spec.rb - passes
```

**Comment by symwell** [comment]
kgilpin fixed this.  It's not a bug in AppMap.  Forem was using a method called `hash` in [`app/models/reaction_category.rb` ](https://github.com/forem/forem/compare/main...symwell:forem:sw/use_appmap_to_create_openapi_doc?expand=1#diff-04ff996d0239ba13016a82bef6991dbb35eee4f0916081acbe9ffeb7878c1884) that doesn’t return a hash code.  This is invalid Ruby.

This error wasn't visible in Forem because the codebase was getting lucky by not using the classes in a way that would cause the error.  AppMap triggered the error.
