### ISSUE TITLE
Undefined method engine? with Rails 5.1.7

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-ruby#364]
With Rails 5.1.7, the following error is encountered:

```
#<NoMethodError: undefined method `engine?' for #<ActionDispatch::Routing::RouteSet::Dispatcher:0x00007fedd33d7d40>>
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/appmap-1.1.0/lib/appmap/handler/rails/request_handler.rb:69:in `block in normalized_path'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:73:in `block in recognize'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:66:in `each'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:66:in `recognize'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/appmap-1.1.0/lib/appmap/handler/rails/request_handler.rb:64:in `normalized_path'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/appmap-1.1.0/lib/appmap/handler/rails/request_handler.rb:20:in `initialize'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/appmap-1.1.0/lib/appmap/handler/rails/request_handler.rb:162:in `new'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/appmap-1.1.0/lib/appmap/handler/rails/request_handler.rb:162:in `before_hook'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/appmap-1.1.0/lib/appmap/hook/method/ruby2.rb:22:in `block in call'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/appmap-1.1.0/lib/appmap/hook/method.rb:125:in `with_disabled_hook'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/appmap-1.1.0/lib/appmap/hook/method/ruby2.rb:22:in `call'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/appmap-1.1.0/lib/appmap/hook/method/ruby2.rb:72:in `block in hook_method_def'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/appmap-1.1.0/lib/appmap/middleware/remote_recording.rb:130:in `call'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rack-2.2.10/lib/rack/sendfile.rb:110:in `call'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
/Users/kgilpin/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

**Comment by kgilpin** [comment]
As a workaround, create the file config/initializers/patch_dispatcher.rb:

```ruby
module ActionDispatch::Routing
    class RouteSet
        class Dispatcher
            def engine?
                false
            end
        end
    end
end
```

**Comment by dividedmind** [comment]
Note upstream support for Ruby 2 ended almost two years ago (and that version of Rails doesn't support Ruby 3). I'll add the fix since it's simple but I'm not sure it's worth the trouble of adding a test for this — I'm struggling to even build this locally.
